name: dog_wiki
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  image_picker: ^0.8.4+3
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Holtwood One SC,
      fonts:
        - asset: fonts/holtwood_one_sc.ttf
  assets:
    - lib/assets/
  uses-material-design: true
